<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'employee_number' => '001',
                'username' => 'ec001',
                'password' => '$2y$12$fWkNavux4Lnaid4kG3rV0eZn/4b9cIBO1D.LO/1yMML.S0Ic3055u',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:55',
                'updated_at' => '2025-11-12 13:36:55',
            ),
            1 => 
            array (
                'id' => 2,
                'employee_number' => '005',
                'username' => 'ea005',
                'password' => '$2y$12$H/9sgdeWdzHQMF0ZatioFO1SbY.PgvncB/rF6Y.S5fdRj4XOEK1N2',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:56',
                'updated_at' => '2025-11-12 13:36:56',
            ),
            2 => 
            array (
                'id' => 3,
                'employee_number' => '009',
                'username' => 'jb009',
                'password' => '$2y$12$hnG8KGJcsWH7hoFyAh/Fse7RXlGnuOylSl6opZM2uKwc5l6QtoqZm',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:56',
                'updated_at' => '2025-11-12 13:36:56',
            ),
            3 => 
            array (
                'id' => 4,
                'employee_number' => '011',
                'username' => 'ec011',
                'password' => '$2y$12$/3w4p3ekV.DyTU2VT46rteEe.LdVXEB/SQcUGZhXdFd7eLARLv.BC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:57',
                'updated_at' => '2025-11-12 13:36:57',
            ),
            4 => 
            array (
                'id' => 5,
                'employee_number' => '187',
                'username' => 'ab187',
                'password' => '$2y$12$Y3NERRHfPAC5IjecWbqLO.aiEDk.G5LkjbyscXnXPvPgMme2iFh8W',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:57',
                'updated_at' => '2025-11-12 13:36:57',
            ),
            5 => 
            array (
                'id' => 6,
                'employee_number' => '014',
                'username' => 'rr014',
                'password' => '$2y$12$vS.vhF8j9cA0jULKWFv.7.hXQ2Nd9Qj9Z/qMLcLj2L4DEDY887t..',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:58',
                'updated_at' => '2025-11-12 13:36:58',
            ),
            6 => 
            array (
                'id' => 7,
                'employee_number' => '015',
                'username' => 'ip015',
                'password' => '$2y$12$ige0JxNIce/K1EIWfOraFeEh/z3sBKDoAons0wnLxdraujNL2wSkW',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:58',
                'updated_at' => '2025-11-12 13:36:58',
            ),
            7 => 
            array (
                'id' => 8,
                'employee_number' => '018',
                'username' => 'pi018',
                'password' => '$2y$12$IKYbN2dLq9kAmPYx0e0UkuoGS5tZRsRtV/Mk6YkqLU4Xdw3436WtO',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:58',
                'updated_at' => '2025-11-12 13:36:58',
            ),
            8 => 
            array (
                'id' => 9,
                'employee_number' => '021',
                'username' => 'aj021',
                'password' => '$2y$12$8ZIwAZzR8hWZSG9Ot7NSKOoGAPK9FiruTmKu95FWQV7ibg1j4cJvS',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:59',
                'updated_at' => '2025-11-12 13:36:59',
            ),
            9 => 
            array (
                'id' => 10,
                'employee_number' => '024',
                'username' => 'll024',
                'password' => '$2y$12$EEhKSH4Lv2JZZ6J91CUqJ.WvFDP28sY7zwZdPfMnd./jdNT.YEs42',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:36:59',
                'updated_at' => '2025-11-12 13:36:59',
            ),
            10 => 
            array (
                'id' => 11,
                'employee_number' => '026',
                'username' => 'ml026',
                'password' => '$2y$12$Ukg9NKn2IYA.NIWMUkhM7u89kma0Bo2YRG9F.2JrdqguCui0LrgWq',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:00',
                'updated_at' => '2025-11-12 13:37:00',
            ),
            11 => 
            array (
                'id' => 12,
                'employee_number' => '028',
                'username' => 'rm028',
                'password' => '$2y$12$rIvDkMcQZP8T5/5rE2oOduyOWk5sCf/TRZE081D8GF36fLwB0j0Xe',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:00',
                'updated_at' => '2025-11-12 13:37:00',
            ),
            12 => 
            array (
                'id' => 13,
                'employee_number' => '029',
                'username' => 'cm029',
                'password' => '$2y$12$izYuPC0IynEM5LRxuACmR./6y9Xi24Hw1SyUGwcnUSlaLlZntLpOK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:01',
                'updated_at' => '2025-11-12 13:37:01',
            ),
            13 => 
            array (
                'id' => 14,
                'employee_number' => '035',
                'username' => 'jp035',
                'password' => '$2y$12$ij4sadpnqTYYDTtNxHplQOLB8dkrpazJQqE3XJiCgjzZbqQ.L8iY2',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:01',
                'updated_at' => '2025-11-12 13:37:01',
            ),
            14 => 
            array (
                'id' => 15,
                'employee_number' => '037',
                'username' => 'sm037',
                'password' => '$2y$12$xwIECT.kuVFt36OmqZ4gx.d9.Z2KqWKYvK5u4pAxMZFZB9b4Tordu',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:01',
                'updated_at' => '2025-11-12 13:37:01',
            ),
            15 => 
            array (
                'id' => 16,
                'employee_number' => '042',
                'username' => 'jl042',
                'password' => '$2y$12$gtKeXizNumhYRifQV2aupuD9BdOVXLqZNxUfkeBS/UkahBwZZiy5a',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:02',
                'updated_at' => '2025-11-12 13:37:02',
            ),
            16 => 
            array (
                'id' => 17,
                'employee_number' => '043',
                'username' => 'gr043',
                'password' => '$2y$12$Ax0RYInpXun7SHuDhjBtZ.PIvjuXd3JaWRVh8nbb4iRGPZpOXTUdG',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:02',
                'updated_at' => '2025-11-12 13:37:02',
            ),
            17 => 
            array (
                'id' => 18,
                'employee_number' => '044',
                'username' => 've044',
                'password' => '$2y$12$BHtIV/6EMx22RyzC0dYmq.ahhIF99LLN/0QFiqj5OyLqvAMTdiwvm',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:03',
                'updated_at' => '2025-11-12 13:37:03',
            ),
            18 => 
            array (
                'id' => 19,
                'employee_number' => '049',
                'username' => 'ld049',
                'password' => '$2y$12$TcGdbO6wvyVjqvNIr9o4Yue4sOnPUoDHG2bGKOTSMSkUQZC7cFmt2',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:03',
                'updated_at' => '2025-11-12 13:37:03',
            ),
            19 => 
            array (
                'id' => 20,
                'employee_number' => '050',
                'username' => 'fa050',
                'password' => '$2y$12$ZT/8U/rMSEGro1wUDDr6SO2WMMHHbDW/mce4VYHcV8lzqxFM126mK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:04',
                'updated_at' => '2025-11-12 13:37:04',
            ),
            20 => 
            array (
                'id' => 21,
                'employee_number' => '051',
                'username' => 'ar051',
                'password' => '$2y$12$FYqHkHlIiAyXdQkMnvxFBePB1tygk/QUGT6Tz.lqvN8Ff.cmkuTMa',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:04',
                'updated_at' => '2025-11-12 13:37:04',
            ),
            21 => 
            array (
                'id' => 22,
                'employee_number' => '052',
                'username' => 'rn052',
                'password' => '$2y$12$c11ZEAHYXqMnOqEpf2n0aeZ6Enrl.OMRdtmYZ5ZXx6aJkLR6wnsry',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:05',
                'updated_at' => '2025-11-12 13:37:05',
            ),
            22 => 
            array (
                'id' => 23,
                'employee_number' => '066',
                'username' => 'av066',
                'password' => '$2y$12$klOIGJTPma6HASP7KtToOeu3aqmHUrcwnN5rXtwme0yMcmLXRbQs.',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:05',
                'updated_at' => '2025-11-12 13:37:05',
            ),
            23 => 
            array (
                'id' => 24,
                'employee_number' => '067',
                'username' => 'ab067',
                'password' => '$2y$12$.mDxXeoXirk7n0381RBiB.c2h9J1axnVjcGDnKhvj7ocihIKFX/YG',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:05',
                'updated_at' => '2025-11-12 13:37:05',
            ),
            24 => 
            array (
                'id' => 25,
                'employee_number' => '068',
                'username' => 'lm068',
                'password' => '$2y$12$rIUZ328Z4sBGUHz9XL8IjuAXSegTGM6hUXMKdAIHJXN2s/Pk.RHTW',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:06',
                'updated_at' => '2025-11-12 13:37:06',
            ),
            25 => 
            array (
                'id' => 26,
                'employee_number' => '073',
                'username' => 'am073',
                'password' => '$2y$12$PSmHYG6wNTy1tERaubKpZernSTMbq8dXKlcIx23W2m6iGPMm4VxCq',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:06',
                'updated_at' => '2025-11-12 13:37:06',
            ),
            26 => 
            array (
                'id' => 27,
                'employee_number' => '074',
                'username' => 'rn074',
                'password' => '$2y$12$fK8LD/.i8cj1FHCdXto8IOlh4f25CLv4Xw3GTMKN6xlVOV74vB36a',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:07',
                'updated_at' => '2025-11-12 13:37:07',
            ),
            27 => 
            array (
                'id' => 28,
                'employee_number' => '077',
                'username' => 'oa077',
                'password' => '$2y$12$WpSCyZwTflbrzo2jCZ4UD.6ONOTaZmTC0cfi6KU54pYE1NAIXCPte',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:07',
                'updated_at' => '2025-11-12 13:37:07',
            ),
            28 => 
            array (
                'id' => 29,
                'employee_number' => '086',
                'username' => 'dd086',
                'password' => '$2y$12$i6yXJy7RBVIYsNvsRdgXNup8QHAxKaRLRHO76sYWlVk8R35ln8Esu',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:08',
                'updated_at' => '2025-11-12 13:37:08',
            ),
            29 => 
            array (
                'id' => 30,
                'employee_number' => '087',
                'username' => 'rr087',
                'password' => '$2y$12$2T6gbSy9syTGtJVmoJ7K1eeDTqFO5MurhQlN9PzLwyaoS.PJFOpEu',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:08',
                'updated_at' => '2025-11-12 13:37:08',
            ),
            30 => 
            array (
                'id' => 31,
                'employee_number' => '090',
                'username' => 'ab090',
                'password' => '$2y$12$Y8yFgKaZnHFnroBkEzx8J.ZJWnZy.KAdyJ3rS2nU46ka5RsTxqPsy',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:08',
                'updated_at' => '2025-11-12 13:37:08',
            ),
            31 => 
            array (
                'id' => 32,
                'employee_number' => '104',
                'username' => 'ta104',
                'password' => '$2y$12$LlILn8L/dVnNUCY4gKhfVe/u7rQjSsm3vSx5FeBRe/Ah1Q9WPTfie',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:09',
                'updated_at' => '2025-11-12 13:37:09',
            ),
            32 => 
            array (
                'id' => 33,
                'employee_number' => '105',
                'username' => 'rp105',
                'password' => '$2y$12$tGcwM.iL17e2E43C34zy4OTsPCKC8k8SCZrL9loJX/myY7eCWFTtm',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:09',
                'updated_at' => '2025-11-12 13:37:09',
            ),
            33 => 
            array (
                'id' => 34,
                'employee_number' => '106',
                'username' => 'hg106',
                'password' => '$2y$12$nkw/K8WY7nBdO3y1rZ6xi.qCteVIWvLYZM/SztF/i6W6MHfzHBhke',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:10',
                'updated_at' => '2025-11-12 13:37:10',
            ),
            34 => 
            array (
                'id' => 35,
                'employee_number' => '108',
                'username' => 'jt108',
                'password' => '$2y$12$pMkwPSym/ydIgi/3FYAVb.lMYgpMAMqJRBNJPbWT8d7Oyp5b5TD3q',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:10',
                'updated_at' => '2025-11-12 13:37:10',
            ),
            35 => 
            array (
                'id' => 36,
                'employee_number' => '112',
                'username' => 'am112',
                'password' => '$2y$12$5W6jcVQ4oRUN1M427dhWCuKsvKY6zWTs5zsgW.INfzFshcTRT1fpi',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:11',
                'updated_at' => '2025-11-12 13:37:11',
            ),
            36 => 
            array (
                'id' => 37,
                'employee_number' => '121',
                'username' => 'fl121',
                'password' => '$2y$12$efQDzeF9G80GQcXZ8GeP8uVTfY2e0Sxm2.cPdQxS0rIxZBivpXC.O',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:11',
                'updated_at' => '2025-11-12 13:37:11',
            ),
            37 => 
            array (
                'id' => 38,
                'employee_number' => '127',
                'username' => 'ho127',
                'password' => '$2y$12$HvTPTIDnHwZZzc3OvBYfe./lV8dPkgvLQ7Ctr4CrAhMduBafIFEWK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:12',
                'updated_at' => '2025-11-12 13:37:12',
            ),
            38 => 
            array (
                'id' => 39,
                'employee_number' => '128',
                'username' => 'jp128',
                'password' => '$2y$12$1nsHFqNslS6oxjuQ06ER5e9rd1eyCHRc6AIKoAku5EWFmmLE9l/Bi',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:12',
                'updated_at' => '2025-11-12 13:37:12',
            ),
            39 => 
            array (
                'id' => 40,
                'employee_number' => '134',
                'username' => 'mv134',
                'password' => '$2y$12$8LqfFPBexAIF/MpIFZDY6.G9g7aYn6w5eC7qDpIUqzzIH0M2t0Ye2',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:12',
                'updated_at' => '2025-11-12 13:37:12',
            ),
            40 => 
            array (
                'id' => 41,
                'employee_number' => '132',
                'username' => 'jg132',
                'password' => '$2y$12$6nlOYGd5PBX1Qv4.aU8BnuldQ6ipxAQzYTMH8KTF9MraX5.HWnqUm',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:13',
                'updated_at' => '2025-11-12 13:37:13',
            ),
            41 => 
            array (
                'id' => 42,
                'employee_number' => '151',
                'username' => 'jd151',
                'password' => '$2y$12$XltFMqIUqvpWX2FzQ1dfauI9vt2YzNMR7.9kY8VZapCyQnhjtKIGe',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:13',
                'updated_at' => '2025-11-12 13:37:13',
            ),
            42 => 
            array (
                'id' => 43,
                'employee_number' => '154',
                'username' => 'jc154',
                'password' => '$2y$12$aOeWyYvWJezf79dr9nzhxu5Ciu/e3vBwpUL8UunFJJHll0Zl.JuTK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:14',
                'updated_at' => '2025-11-12 13:37:14',
            ),
            43 => 
            array (
                'id' => 44,
                'employee_number' => '156',
                'username' => 'lb156',
                'password' => '$2y$12$nEyfSzqgVPJoo.EU9LxO2eo3hzKM195pPOuxt/iWNDr6n9oeMl/f.',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:14',
                'updated_at' => '2025-11-12 13:37:14',
            ),
            44 => 
            array (
                'id' => 45,
                'employee_number' => '160',
                'username' => 'ra160',
                'password' => '$2y$12$HbEGYOZn5De409SjJyVdPuV/u/8eyI1NCxKsxp.WJ0py0aWYfH3Ki',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:15',
                'updated_at' => '2025-11-12 13:37:15',
            ),
            45 => 
            array (
                'id' => 46,
                'employee_number' => '161',
                'username' => 'mm161',
                'password' => '$2y$12$WktQEjJEtAHvpiz4k2ZZz.B8APBTHnl0MD6Nagaj1aAFWeIGmMXGm',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:15',
                'updated_at' => '2025-11-12 13:37:15',
            ),
            46 => 
            array (
                'id' => 47,
                'employee_number' => '162',
                'username' => 'fm162',
                'password' => '$2y$12$bit2H7IBVt5UQe29.CCuQesL1PDdMqcLIWsX2oI9v6iHgZ18FCjPq',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:16',
                'updated_at' => '2025-11-12 13:37:16',
            ),
            47 => 
            array (
                'id' => 48,
                'employee_number' => '163',
                'username' => 'rm163',
                'password' => '$2y$12$PupIEXy2vHgCEfTVVGDWneh6GLFGahuZmy0t9XV4IGAqAGFtrCxqS',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:16',
                'updated_at' => '2025-11-12 13:37:16',
            ),
            48 => 
            array (
                'id' => 49,
                'employee_number' => '172',
                'username' => 'cg172',
                'password' => '$2y$12$tlaSHPdV3gt/ky4QjKOKdu0avYaOm/z8/mwYi6HVXYH3TBoPUgUtK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:16',
                'updated_at' => '2025-11-12 13:37:16',
            ),
            49 => 
            array (
                'id' => 50,
                'employee_number' => '173',
                'username' => 'ra173',
                'password' => '$2y$12$w1s1usikrXYM3YOvGgVUh.cXLYnwK/nLymXhjwjGt4kGGf2lAbEKe',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:17',
                'updated_at' => '2025-11-12 13:37:17',
            ),
            50 => 
            array (
                'id' => 51,
                'employee_number' => '175',
                'username' => 'rc175',
                'password' => '$2y$12$ppSng0zdspukoiXQDxcHaOlSNp3cR6RAEAsrWPDEvDsyzPBmcx3C2',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:17',
                'updated_at' => '2025-11-12 13:37:17',
            ),
            51 => 
            array (
                'id' => 52,
                'employee_number' => '181',
                'username' => 'ea181',
                'password' => '$2y$12$GvVAgqgMTj3bRmgGh5NHZ.57RmrwO.speSgu7CZf1.f7PGvb/HmQO',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:18',
                'updated_at' => '2025-11-12 13:37:18',
            ),
            52 => 
            array (
                'id' => 53,
                'employee_number' => '183',
                'username' => 'js183',
                'password' => '$2y$12$a880LkEwxXtSDKjJlh9LBewCuOQEC2K8u7QM.CYlJ52P.Cpa9z5X2',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:18',
                'updated_at' => '2025-11-12 13:37:18',
            ),
            53 => 
            array (
                'id' => 54,
                'employee_number' => '185',
                'username' => 'jc185',
                'password' => '$2y$12$hmX6vOMY68HMClj.befkmu8R7/sxIVgPWZS4oDsKfs/Qbo/vI/ydC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:19',
                'updated_at' => '2025-11-12 13:37:19',
            ),
            54 => 
            array (
                'id' => 55,
                'employee_number' => '188',
                'username' => 'rp188',
                'password' => '$2y$12$RtwWrjpMgua6DZV5dPz3Vesd9XiY5PgT7oW95g8Fm8AN3vtM2V6ZC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:19',
                'updated_at' => '2025-11-12 13:37:19',
            ),
            55 => 
            array (
                'id' => 56,
                'employee_number' => '189',
                'username' => 'kr189',
                'password' => '$2y$12$GRSGCMvXLKnR8oUkzZxsAeriIv1ofl4Ze4ArKQEay/.z3.BzhKUhC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:19',
                'updated_at' => '2025-11-12 13:37:19',
            ),
            56 => 
            array (
                'id' => 57,
                'employee_number' => '191',
                'username' => 'md191',
                'password' => '$2y$12$kIn/WQSQLYrsBcle1.GPdOwSpegp0OML4goitjTcemJ.LdzETOJMC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:20',
                'updated_at' => '2025-11-12 13:37:20',
            ),
            57 => 
            array (
                'id' => 58,
                'employee_number' => '192',
                'username' => 'jm192',
                'password' => '$2y$12$I8PUym1qAD5TQQ8PZxlk9O6iRDg7oMavNc40Fkk2KsDNu/DTDL1I6',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:20',
                'updated_at' => '2025-11-12 13:37:20',
            ),
            58 => 
            array (
                'id' => 59,
                'employee_number' => '198',
                'username' => 'av198',
                'password' => '$2y$12$7szmAXQ1R7Bp5v3up2R6.OypKRKAMnlnwiKPVz1yLvNTzdyh.7Lp.',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:21',
                'updated_at' => '2025-11-12 13:37:21',
            ),
            59 => 
            array (
                'id' => 60,
                'employee_number' => '199',
                'username' => 'jp199',
                'password' => '$2y$12$6RSRcqbqgSnxmHjkx6xEeeU8Eo99hOWjEMWD7fOEmu8/COye2PImm',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:21',
                'updated_at' => '2025-11-12 13:37:21',
            ),
            60 => 
            array (
                'id' => 61,
                'employee_number' => '200',
                'username' => 'jc200',
                'password' => '$2y$12$Ef/Nop9Z7HZZ9KSEeodiiOnLpRxTd1hMbyO8EfBVFcKUb2EdJ7mOG',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:22',
                'updated_at' => '2025-11-12 13:37:22',
            ),
            61 => 
            array (
                'id' => 62,
                'employee_number' => '229',
                'username' => 'md229',
                'password' => '$2y$12$DiA4NCGUw98gaqwN7WB1Fukq37i/gU.2Jctw2nvP7Cy4T70/y6tVO',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:22',
                'updated_at' => '2025-11-12 13:37:22',
            ),
            62 => 
            array (
                'id' => 63,
                'employee_number' => '214',
                'username' => 'jb214',
                'password' => '$2y$12$u7HvbtVOWxlj1ytKa/3DrOR7a87eIc/bgNkr3x5Wz/dhUCsxzxkRG',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:23',
                'updated_at' => '2025-11-12 13:37:23',
            ),
            63 => 
            array (
                'id' => 64,
                'employee_number' => '215',
                'username' => 'rr215',
                'password' => '$2y$12$m9DFWBr49r5LuqvYGhhQ8eqPmZMiKJMj/WCDCThF4FQG8k.EfL47i',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:23',
                'updated_at' => '2025-11-12 13:37:23',
            ),
            64 => 
            array (
                'id' => 65,
                'employee_number' => '216',
                'username' => 'bd216',
                'password' => '$2y$12$uQ.M4iVY2oajDbHJRrYWguWHNpDxrYi4zzNt/guHdCGIZ6vxy6rZy',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:23',
                'updated_at' => '2025-11-12 13:37:23',
            ),
            65 => 
            array (
                'id' => 66,
                'employee_number' => '218',
                'username' => 'et218',
                'password' => '$2y$12$7uQ/ZVbZYS3qYUtd8uWYJOEcX3qDDjvFL6K5wJPbWrjGDsZvzR2QO',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:24',
                'updated_at' => '2025-11-12 13:37:24',
            ),
            66 => 
            array (
                'id' => 67,
                'employee_number' => '219',
                'username' => 'pd219',
                'password' => '$2y$12$LrtDyj2xrL1EC6vArPeS/uuozLqCwgYklzgHRV.tsttGl1CEN6D..',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:24',
                'updated_at' => '2025-11-12 13:37:24',
            ),
            67 => 
            array (
                'id' => 68,
                'employee_number' => '220',
                'username' => 'em220',
                'password' => '$2y$12$keRDzKGKncJK43ABL.3CAeaNftonfi4jMxauW5X5YoZttgpX.BbwW',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:25',
                'updated_at' => '2025-11-12 13:37:25',
            ),
            68 => 
            array (
                'id' => 69,
                'employee_number' => '222',
                'username' => 'ht222',
                'password' => '$2y$12$Y.EKtlh6zuhFr0EfiO2Dcu1YicPR6SUbCtQgHu13bV2p1u8YPhKY6',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:25',
                'updated_at' => '2025-11-12 13:37:25',
            ),
            69 => 
            array (
                'id' => 70,
                'employee_number' => '223',
                'username' => 'rc223',
                'password' => '$2y$12$Nj6D/mCAhwQl3vcsq77v9OCjeXVoaXoFGnUcnXyHtDWCF2.f/I8TC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:26',
                'updated_at' => '2025-11-12 13:37:26',
            ),
            70 => 
            array (
                'id' => 71,
                'employee_number' => '227',
                'username' => 'ct227',
                'password' => '$2y$12$yB7h4A2tPqMvD8Mi.3J0VeiEl0SPw1thMQSqGnwyHHntRJBuZcHdu',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:26',
                'updated_at' => '2025-11-12 13:37:26',
            ),
            71 => 
            array (
                'id' => 72,
                'employee_number' => '232',
                'username' => 'ob232',
                'password' => '$2y$12$ajzx.mNREr7nAs8xi5H77Oi7MRuUpExinhpU9F1FJzmmOmplAFVce',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:26',
                'updated_at' => '2025-11-12 13:37:26',
            ),
            72 => 
            array (
                'id' => 73,
                'employee_number' => '2401',
                'username' => 'gs2401',
                'password' => '$2y$12$7S.B9oWvWk6.CF97z0cM3eYTsAC9AQigq6NyXrjcMSMzD0OzLJzPO',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:27',
                'updated_at' => '2025-11-12 13:37:27',
            ),
            73 => 
            array (
                'id' => 74,
                'employee_number' => '2402',
                'username' => 'cs2402',
                'password' => '$2y$12$fByPzPp6mnOAOkCbK5ZCH.jklRLfhDYBRcMbCjSLqTGPCZ/hu01Vi',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:27',
                'updated_at' => '2025-11-12 13:37:27',
            ),
            74 => 
            array (
                'id' => 75,
                'employee_number' => '2403',
                'username' => 'ls2403',
                'password' => '$2y$12$0JhRKsWzld7nLc5jIldNTeG9dAs63fu6Ay.X1E.jRcZsYrszNDMay',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:28',
                'updated_at' => '2025-11-12 13:37:28',
            ),
            75 => 
            array (
                'id' => 76,
                'employee_number' => '2404',
                'username' => 'jd2404',
                'password' => '$2y$12$MDPCcoK.XgZ3l0z2SO6h2.taCzsSl.Z4Fe/1kodyHQ50aKUaEbPoK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:28',
                'updated_at' => '2025-11-12 13:37:28',
            ),
            76 => 
            array (
                'id' => 77,
                'employee_number' => '2405',
                'username' => 'jl2405',
                'password' => '$2y$12$gEn6Bl5DLQOr/qNvUBMYI.izWK7HMnaQ/n.z2bdqiD7lhWD/5bNc.',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:29',
                'updated_at' => '2025-11-12 13:37:29',
            ),
            77 => 
            array (
                'id' => 78,
                'employee_number' => '2406',
                'username' => 'jb2406',
                'password' => '$2y$12$En8UA3swCaT7x7BoLq.dD..08xkstrbvSWm/JuKGZhZKVG7Ec1WFS',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:29',
                'updated_at' => '2025-11-12 13:37:29',
            ),
            78 => 
            array (
                'id' => 79,
                'employee_number' => '2407',
                'username' => 'rt2407',
                'password' => '$2y$12$mksicPM/bLe9lZVTcwQQkOKrrUQZKfcSwfH7FfranueQNAoDQdbay',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:30',
                'updated_at' => '2025-11-12 13:37:30',
            ),
            79 => 
            array (
                'id' => 80,
                'employee_number' => '2408',
                'username' => 'ac2408',
                'password' => '$2y$12$POQhjU4rOjVEhv3mKlOLxuhfmJBPNYDAkNoDRPEW1KhG/gnIAlZ7C',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:30',
                'updated_at' => '2025-11-12 13:37:30',
            ),
            80 => 
            array (
                'id' => 81,
                'employee_number' => '2411',
                'username' => 'jo2411',
                'password' => '$2y$12$qcnGafqPx8kysoaPCqdpX.zI9eWtxURj/tql4emz2jW9A96qZHJIq',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:30',
                'updated_at' => '2025-11-12 13:37:30',
            ),
            81 => 
            array (
                'id' => 82,
                'employee_number' => '2414',
                'username' => 'rc2414',
                'password' => '$2y$12$xDq3D7tBvh/AdC7aH6thQu9Dht8bnm/nA1IEvhAjxm4isz61G7JOO',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:31',
                'updated_at' => '2025-11-12 13:37:31',
            ),
            82 => 
            array (
                'id' => 83,
                'employee_number' => '2416',
                'username' => 'ja2416',
                'password' => '$2y$12$3.jV/0qr0O7ldIHIkLa2N.5YQEM9H7THNec8H6Ql9KoeYVKxYJQQi',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:31',
                'updated_at' => '2025-11-12 13:37:31',
            ),
            83 => 
            array (
                'id' => 84,
                'employee_number' => '2417',
                'username' => 'ab2417',
                'password' => '$2y$12$XPGYQ9uTA/ol2BifGBwfoe9RUT/BC9Bk6hy/W6RbgkD9VOg6VX68q',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:32',
                'updated_at' => '2025-11-12 13:37:32',
            ),
            84 => 
            array (
                'id' => 85,
                'employee_number' => '2418',
                'username' => 'gb2418',
                'password' => '$2y$12$8Mi7D1uYrx8bB0RKI2Vm3u9FdVKwOGb74nP5XQesWsuBI2/QHmyQC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:32',
                'updated_at' => '2025-11-12 13:37:32',
            ),
            85 => 
            array (
                'id' => 86,
                'employee_number' => '2419',
                'username' => 'cb2419',
                'password' => '$2y$12$d01.kE/pYOBXDQ20BdLZ.OfRZu7EdHoFcMzf6E3InJaIfYj.F92ca',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:33',
                'updated_at' => '2025-11-12 13:37:33',
            ),
            86 => 
            array (
                'id' => 87,
                'employee_number' => '2421',
                'username' => 'jl2421',
                'password' => '$2y$12$itinFbdgETNrDgmbcwCnuO0XIOuLSe3seWlhDQASsVCgbLvS9VvQi',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:33',
                'updated_at' => '2025-11-12 13:37:33',
            ),
            87 => 
            array (
                'id' => 88,
                'employee_number' => '2422',
                'username' => 'hg2422',
                'password' => '$2y$12$Y6UBeE1dC9eErYiEhtC1E.xm9AlOatsQRnG0jrk7yzkgBm0e59J1S',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:33',
                'updated_at' => '2025-11-12 13:37:33',
            ),
            88 => 
            array (
                'id' => 89,
                'employee_number' => '2423',
                'username' => 'dp2423',
                'password' => '$2y$12$b8z39DrgXjjZIB9BN5TBGOMZaFwljgUmtIBSRm7oMVsIBiLlhYJk6',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:34',
                'updated_at' => '2025-11-12 13:37:34',
            ),
            89 => 
            array (
                'id' => 90,
                'employee_number' => '2424',
                'username' => 'rp2424',
                'password' => '$2y$12$EW7NiKerqCr2hJ669saoLOCAvr5Zbux8xg5E7tmIIEwZyncX56iQ6',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:34',
                'updated_at' => '2025-11-12 13:37:34',
            ),
            90 => 
            array (
                'id' => 91,
                'employee_number' => '2425',
                'username' => 'nb2425',
                'password' => '$2y$12$dPp7lnMlTb7ukxJiNbK8SO7SIx.HD.aQaCtycMWoPj4Ki0ls6UC/u',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:35',
                'updated_at' => '2025-11-12 13:37:35',
            ),
            91 => 
            array (
                'id' => 92,
                'employee_number' => '2526',
                'username' => 'mf2526',
                'password' => '$2y$12$K9BmrGP7b7kj1sJY0HN7dehlEWJCBJqQVyrxfngomd0kTliRgcSmK',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:35',
                'updated_at' => '2025-11-12 13:37:35',
            ),
            92 => 
            array (
                'id' => 93,
                'employee_number' => '2527',
                'username' => 'ch2527',
                'password' => '$2y$12$GszSuTj/Ri0K4GWDOasqfO7gYBJNfn1vuAMshg6xhifR8PO1G6vtG',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'status' => 1,
                'email_verified_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-11-12 13:37:36',
                'updated_at' => '2025-11-12 13:37:36',
            ),
            93 => 
            array (
                'id' => 94,
                'employee_number' => '0000',
                'username' => 'administrator',
                'password' => '$2y$12$n.Se.dWvSxQ9UjQTBllJk.75oRiFPUa9.ahtUSMFycJzLzAAgvngC',
                'password_changed_at' => NULL,
                'must_change_password' => 0,
                'last_login_at' => '2026-03-19 01:03:35',
                'last_login_ip' => '127.0.0.1',
                'status' => 1,
                'email_verified_at' => '2026-03-19 01:02:13',
                'deleted_at' => NULL,
                'created_at' => '2026-03-19 01:02:13',
                'updated_at' => '2026-03-19 01:03:35',
            ),
        ));
        
        
    }
}